sudo: required
services:
  - docker

before_install:
  - docker build -t ghola/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ghola/react-test npm test

after_success:
  - docker build -t ghola/multi-client ./client
  - docker build -t ghola/multi-nginx ./nginx
  - docker build -t ghola/multi-server ./server
  - docker build -t ghola/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ghola/multi-client
  - docker push ghola/multi-nginx
  - docker push ghola/multi-server
  - docker push ghola/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-018653512379"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
    